global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: "memory-bank-monitoring"
    static_configs:
      - targets: ["localhost:3001"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "memory-bank-security"
    static_configs:
      - targets: ["localhost:3002"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "memory-bank-api"
    static_configs:
      - targets: ["localhost:3003"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
